<?php 
/*
Plugin Name: Enquire Feedback Form
Plugin URI: https://drive.google.com
Description: This plugin create a custom form to enquire the feedbacks on frontend by using shortcode.
Version: 1.1.0
Author: Andre Verona
Author URI: https://andreverona.com
Text Domain: enfb
Generated By: http://andreverona.com
*/

if ( ! defined( 'WPINC' ) ) {die;} // end if
// Define Our Constants
define('ENFB_CORE_INC',dirname( __FILE__ ).'/assets/inc/');
define('ENFB_CORE_IMG',plugins_url( 'assets/img/', __FILE__ ));
define('ENFB_CORE_CSS',plugins_url( 'assets/css/', __FILE__ ));
define('ENFB_CORE_JS',plugins_url( 'assets/js/', __FILE__ ));

add_action('init', 'init_enquire_feedback');

function init_enquire_feedback(){
	$args = array(
		'public'    => true,
		'label'     => __( 'Feedbacks', 'enfb' ),
		'exclude_from_search' => true,
		'menu_icon' => 'dashicons-book',
		'supports'  => array( 'title' ),
		'register_meta_box_cb' => 'enfb_feedback_metabox'
	);
	register_post_type( 'enfb_feedback', $args );

	add_shortcode ('enfb_form', 'enfb_form_display' );
	add_shortcode ('enfb_feedbacks', 'enfb_feedbacks_list');
}
/*
*
*  Register JS/Jquery Ready
*
*/
function enfb_register_core_js_css(){

	wp_register_style('enfb-style', ENFB_CORE_CSS . 'style.css');
	// Register Core Plugin JS	
	wp_register_script('enfb-script', ENFB_CORE_JS . 'script.js',array('jquery'), false, true);
	wp_localize_script('enfb-script', 'enfb', array('ajaxurl'=>admin_url('admin-ajax.php')), false, true);

};
add_action( 'wp_enqueue_scripts', 'enfb_register_core_js_css' );    

add_action( 'wp_ajax_enfb_feedback_submit', 'enfb_feedback_submit' );
add_action( 'wp_ajax_nopriv_enfb_feedback_submit', 'enfb_feedback_submit' );
function enfb_feedback_submit(){	

	if (wp_verify_nonce( $_POST['enfb_nonce'], 'enfb_nonce' )){

		$feedback = array(
				'post_title'  => sanitize_text_field($_POST['enfb_subject']),
				'post_content'=>  sanitize_textarea_field($_POST['enfb_message']),
				'post_status' =>  'publish',
				'post_type'   =>  'enfb_feedback',
				'meta_input'  => array(
						'enfb_fname' => sanitize_text_field($_POST['enfb_fname']),
						'enfb_lname' => sanitize_text_field($_POST['enfb_lname']),
						'enfb_email' => sanitize_text_field($_POST['enfb_email'])
					)
			);

		if(isset($_POST['enfb_user'])) $feedback['post_author'] = $_POST['enfb_user'];

		$id = wp_insert_post($feedback);
		
		wp_send_json(
			array(
				'status' =>true, 
				'message'=>__('Thank you for sending us your feedback.', 'enfb')
			)
		);
	}else{
		wp_send_json(
			array(
				'status' =>false, 
				'message'=>__('Sorry, you should send the feedback from the form.', 'enfb')
			)
		);
	}

	wp_die();
}

add_action( 'wp_ajax_enfb_get_feedback', 'enfb_get_feedback' );
function enfb_get_feedback(){
	if(!current_user_can('administrator')) wp_die(__('Only administrator can see the entry details.', 'enfb'));

	if(isset($_GET['id'])){
		$entry_id = $_GET['id'];
		$entry = get_post($entry_id);
		?>
		<div class="enfb_info">
			<p><?php _e('First Name', 'enfb');?> : <?php esc_html_e(get_post_meta($entry->ID, 'enfb_fname', true));?></p>
			<p><?php _e('Last Name', 'enfb');?> : <?php esc_html_e(get_post_meta($entry->ID, 'enfb_lname', true));?></p>
			<p><?php _e('Email', 'enfb');?> : <?php esc_html_e(get_post_meta($entry->ID, 'enfb_email', true));?></p>
			<p><?php _e('Subject', 'enfb');?> : <?php esc_html_e($entry->post_title);?></p>
			<p><?php _e('Message', 'enfb');?> : <div><?php echo nl2br($entry->post_content);?></div></p>
		</div>
		<?php
	}
	wp_die();
}


function enfb_form_display($atts){
	extract(shortcode_atts(array(
		'title'=> __('Submit your feedback', 'enfb'),
		'submit'=> __('Submit', 'enfb')
	),$atts));
	wp_enqueue_style('enfb-style');
	wp_enqueue_script('enfb-script');

	$out ='';
	$out .= '<div id="enfb_feedback_form_wrap" class="enfb-form-wrap">';
	$out .= '<h2>'.$title.'</h2>';
	$out .= '<div class="enfb_results"></div>';
	$out .= '<form id="enfb_feedback_form">';

	$default_values = array();
	if(is_user_logged_in()){
		$current_user = wp_get_current_user();
		$default_values['enfb_fname'] = $current_user->user_firstname;
		$default_values['enfb_lname'] = $current_user->user_lastname;
		$default_values['enfb_email'] = $current_user->user_email;
		$out .= '<input type="hidden" name="enfb_user" class="enfb_field" value="'.$current_user->ID.'"/>';
	}
	$fields = array(
		'enfb_fname'=>    __('First name', 'enfb'),
		'enfb_lname'=>    __('Last name', 'enfb'),
		'enfb_email'=>    __('Email', 'enfb'),
		'enfb_subject'=>  __('Subject', 'enfb'),
		'enfb_message'=>  __('Message', 'enfb')
	);
	foreach($fields as $key=>$field){
		$out .='<div class="enfb_field_wrap">';
		$out .='<label for="'.$key.'">'.$field.'<span class="asterik">*</span></label>';
		$value = '';
		if($key != 'enfb_message' && $key != 'enfb_subject' && is_user_logged_in()) $value = $default_values[$key];
		if($key != 'enfb_message'){
			$out .='<input type="text" id="'.$key.'" name="'.$key.'" class="enfb_field '.$key.'" value="'.$value.'"/>';
		}else{
			$out .='<textarea id="'.$key.'" name="'.$key.'" class="enfb_field '.$key.'"></textarea>';
		}

		$out .='</div>';
	}
	$out .= wp_nonce_field( 'enfb_nonce', 'enfb_nonce', false, false );
	
	$out .= '<p><button type="submit" id="submit_btn">'.$submit.'</button></p>';        
	$out .= '</form>';
	
	$out .='</div><!-- enfb_feedback_form_wrap -->';  

	return apply_filters('enfb_feedback_form_html_output', $out);
}

function enfb_feedbacks_list($atts){
	if(!current_user_can('administrator')) return __('This shortcode is available only for admins.', 'enfb');
	
	wp_enqueue_style('jquery-ui');
	wp_enqueue_style('enfb-style');
	wp_enqueue_script('enfb-script');

	ob_start();
	$paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;
	$args = array(
		'post_type'=>'enfb_feedback',
		'posts_per_page' => 5,
		'paged' => $paged
	);
	$entries = new WP_Query($args);
	?>
	<div class="enfb_entries_wrap">
		<table class="enfb_entries">
			<thead>
				<th><?php _e('Subject', 'enfb');?></th>
				<th><?php _e('First Name', 'enfb');?></th>
				<th><?php _e('Last Name', 'enfb');?></th>
				<th><?php _e('Email', 'enfb');?></th>
			</thead>
			<tbody>
			<?php foreach($entries->posts as $entry):?>
				<tr class="entry_link" data-id="<?php echo $entry->ID;?>">
					<td><?php echo $entry->post_title;?></td>
					<td><?php echo get_post_meta($entry->ID, 'enfb_fname', true);?></td>
					<td><?php echo get_post_meta($entry->ID, 'enfb_lname', true);?></td>
					<td><?php echo get_post_meta($entry->ID, 'enfb_email', true);?></td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
		<div class="pagination">
		<?php 
		echo paginate_links( array(
				'base'         => str_replace( 999999999, '%#%', esc_url( get_pagenum_link( 999999999 ) ) ),
				'total'        => $entries->max_num_pages,
				'current'      => max( 1, get_query_var( 'paged' ) ),
				'format'       => '?paged=%#%',
				'show_all'     => false,
				'type'         => 'plain',
				'end_size'     => 2,
				'mid_size'     => 1,
				'prev_next'    => true,
				'prev_text'    => sprintf( '<i></i> %1$s', __( 'Prev', 'enfb' ) ),
				'next_text'    => sprintf( '%1$s <i></i>', __( 'Next', 'enfb' ) ),
				'add_args'     => false,
				'add_fragment' => '',
			) 
		);
		?>
		</div>
		<div class="enfb_popup" title="Entry detail">
			<div class="close">✕</div>
			<div class="enfb_content"></div>
		</div>
	</div>
	<?php
	$content = ob_get_contents();
	ob_get_clean();
	
	return $content;
}

function enfb_feedback_metabox(){
	add_meta_box( 'enfb_metabox', esc_html__( 'Feedback submission', 'enfb' ), 'enfb_meta_box_callback', 'enfb_feedback', 'advanced', 'high' );
}
//Add field
function enfb_meta_box_callback( $post ) {
	?>
	<div class="field_wrap">
		<label for="enfb_fname" style="width:150px; display:inline-block;"><?php _e('First Name', 'text-domain');?></label>

		<input type="text" name="enfb_fname" id="enfb_fname" class="enfb_field" value="<?php _e(get_post_meta( $post->ID, 'enfb_fname', true ));?>" style="width:300px;"/>
	</div>

	<div class="field_wrap">
		<label for="enfb_lname" style="width:150px; display:inline-block;"><?php _e('Last Name', 'text-domain');?></label>

		<input type="text" name="enfb_lname" id="enfb_lname" class="enfb_field" value="<?php _e(get_post_meta( $post->ID, 'enfb_lname', true ));?>" style="width:300px;"/>
	</div>

	<div class="field_wrap">
		<label for="enfb_subject" style="width:150px; display:inline-block;"><?php _e('Subject', 'text-domain');?></label>

		<input type="text" name="enfb_subject" id="enfb_subject" class="enfb_field" value="<?php _e( $post->post_title);?>" style="width:300px;"/>
	</div>

	<div class="field_wrap">
		<label for="enfb_email" style="width:150px; display:inline-block;"><?php _e('Email', 'text-domain');?></label>

		<input type="email" name="enfb_email" id="enfb_email" class="enfb_field" value="<?php _e(get_post_meta( $post->ID, 'enfb_email', true ));?>" style="width:300px;"/>
	</div>

	<div class="field_wrap">
		<label for="enfb_message" style="width:150px; display:inline-block;"><?php _e('Message', 'text-domain');?></label>

		<textarea name="enfb_message" id="enfb_message" class="enfb_field" style="width:300px;"><?php echo esc_textarea($post->post_content);?></textarea>
	</div>
	<style>.field_wrap{display:flex; margin: 10px auto;}</style>
	<?php
}

add_action('save_post', 'enfb_save_metabox', 10, 2);
function enfb_save_metabox($post_id, $post){
	// Return if the user doesn't have edit permissions.
	if ( ! current_user_can( 'edit_post', $post_id ) ) {
		return $post_id;
	}
	if($_POST && $post->post_type == 'enfb_feedback'){
		$feedback = array(
				'ID'		  => $post_id,
				'post_title'  => sanitize_text_field($_POST['enfb_subject']),
				'post_content'=>  sanitize_textarea_field($_POST['enfb_message']),
				'meta_input'  => array(
						'enfb_fname' => sanitize_text_field($_POST['enfb_fname']),
						'enfb_lname' => sanitize_text_field($_POST['enfb_lname']),
						'enfb_email' => sanitize_text_field($_POST['enfb_email'])
					)
			);
		remove_action('save_post', 'enfb_save_metabox');
		wp_update_post($feedback);
		add_action('save_post', 'enfb_save_metabox');
	}else{
		return $post_id;
	}
}